name: ree_cat_house
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

#--------------------------- Packages ---------------------------#
dependencies:
  flutter:
    sdk: flutter

# Utilitfty Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  


#icons Packages
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

# State Management 
  #provider: ^6.0.5
  get: ^4.6.5
  get_storage: ^2.1.1

# Product Specific 
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1

#firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^6.1.6




# -------------------------- ./ Packages  End -------------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

#--------------------------- Local Assets ---------------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/

# -------------------------- ./ Local Fonts -------------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
# -------------------------- ./ Local Assets End -------------------------- #