// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeze3CFXhNwqUP95KvbtFoMyFwNeE_Jlc',
    appId: '1:330478168049:web:eb22a6ceeed59684b74650',
    messagingSenderId: '330478168049',
    projectId: 'ecommerceapp-1ec72',
    authDomain: 'ecommerceapp-1ec72.firebaseapp.com',
    storageBucket: 'ecommerceapp-1ec72.firebasestorage.app',
    measurementId: 'G-Y6SDK684SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbhACOs2xv1e1QSKfZ53GxUXW4q1IVk4',
    appId: '1:330478168049:android:fb0ad01013c86e53b74650',
    messagingSenderId: '330478168049',
    projectId: 'ecommerceapp-1ec72',
    storageBucket: 'ecommerceapp-1ec72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcdq1eWJWURrSiiPV18VP0M9JP-EJPPA',
    appId: '1:330478168049:ios:cbff93890f120df8b74650',
    messagingSenderId: '330478168049',
    projectId: 'ecommerceapp-1ec72',
    storageBucket: 'ecommerceapp-1ec72.firebasestorage.app',
    androidClientId: '330478168049-p412epe1npkai1kua5o6v723rmgtpik4.apps.googleusercontent.com',
    iosClientId: '330478168049-qanue6dnvdrrdakkd74aelftvm6chgjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.reeCatHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeze3CFXhNwqUP95KvbtFoMyFwNeE_Jlc',
    appId: '1:330478168049:web:d3f6072a1f15a155b74650',
    messagingSenderId: '330478168049',
    projectId: 'ecommerceapp-1ec72',
    authDomain: 'ecommerceapp-1ec72.firebaseapp.com',
    storageBucket: 'ecommerceapp-1ec72.firebasestorage.app',
    measurementId: 'G-R5861FP9R0',
  );
}